from __future__ import annotations

from textual import work
from textual.app import App, ComposeResult
from textual.containers import Horizontal, Vertical
from textual.widgets import DataTable, Footer, Header, Input, Static, TextArea, Tree

from asksql.llm import generate_sql
from asksql.safety import is_read_only
from asksql.sqlite import DEFAULT_LIMIT, inspect, limited_query, preview_table, quote_identifier, schema


class AskSqlApp(App[None]):
    CSS = """
    Screen {
        layout: vertical;
    }

    #top {
        height: 58%;
    }

    #bottom {
        height: 1fr;
    }

    #main {
        height: 1fr;
    }

    #schema {
        width: 34;
        border: solid $primary;
    }

    #work {
        width: 1fr;
    }

    #question {
        border: solid $accent;
        height: 3;
    }

    #sql {
        border: solid $success;
        height: 1fr;
    }

    #status {
        height: 1;
        color: $text-muted;
        padding: 0 1;
    }

    #results {
        height: 1fr;
        border: solid $secondary;
    }
    """

    BINDINGS = [
        ("ctrl+q", "quit", "Quit"),
        ("ctrl+enter", "run_editor_sql", "Run SQL"),
        ("tab", "focus_next", "Next pane"),
        ("shift+tab", "focus_previous", "Previous pane"),
        ("f2", "focus_ask", "Ask AI"),
        ("f3", "focus_sql", "Edit SQL"),
        ("f5", "run_editor_sql", "Run SQL"),
        ("ctrl+r", "refresh_schema", "Refresh schema"),
    ]

    def __init__(self, db_url: str, model: str, limit: int = DEFAULT_LIMIT) -> None:
        super().__init__()
        self.db_url = db_url
        self.model = model
        self.limit = limit

    def compose(self) -> ComposeResult:
        yield Header(show_clock=True)
        with Vertical(id="main"):
            with Horizontal(id="top"):
                yield Tree("Schema - select table to preview", id="schema")
                with Vertical(id="work"):
                    yield Input(placeholder="Ask AI - type a question, then press Enter", id="question")
                    yield TextArea("select * from customers limit 10", language="sql", id="sql")
                    yield Static("Tab/Shift+Tab move | Enter generates SQL | Ctrl+Enter runs SQL | Ctrl+Q quits", id="status")
            with Vertical(id="bottom"):
                yield DataTable(id="results")
        yield Footer()

    def on_mount(self) -> None:
        self._load_schema_tree()
        self.query_one("#sql", TextArea).focus()
        self._set_status("Ready - Tab to move, Ctrl+Enter to run SQL, Enter in Ask AI to generate SQL.")

    def on_input_submitted(self, event: Input.Submitted) -> None:
        question = event.value.strip()
        if question:
            self.ask(question)

    def on_tree_node_selected(self, event: Tree.NodeSelected[object]) -> None:
        if isinstance(event.node.data, str):
            self.preview(event.node.data)

    def action_refresh_schema(self) -> None:
        self._load_schema_tree()

    def action_focus_next(self) -> None:
        self.screen.focus_next()

    def action_focus_previous(self) -> None:
        self.screen.focus_previous()

    def action_focus_ask(self) -> None:
        self.query_one("#question", Input).focus()

    def action_focus_sql(self) -> None:
        self.query_one("#sql", TextArea).focus()

    def action_run_editor_sql(self) -> None:
        self.run_sql(self.query_one("#sql", TextArea).text)

    @work(thread=True)
    def ask(self, question: str) -> None:
        self.call_from_thread(self._set_status, f"Asking {self.model}: {question}")
        try:
            sql = generate_sql(self.model, schema(self.db_url), question)
            if not is_read_only(sql):
                self.call_from_thread(self._set_status, "Refused non-read-only SQL generated by AI.")
                self.call_from_thread(self._set_sql, sql)
                return
        except Exception as exc:
            self.call_from_thread(self._set_status, f"Error: {exc}")
            return
        self.call_from_thread(self._set_sql, sql)
        self.call_from_thread(self._set_status, "Generated SQL. Review or edit it, then press Ctrl+Enter to run.")
        self.call_from_thread(self.action_focus_sql)

    @work(thread=True)
    def run_sql(self, sql: str, source: str = "Manual SQL") -> None:
        if not is_read_only(sql):
            self.call_from_thread(self._set_status, "Refused non-read-only SQL.")
            return
        self.call_from_thread(self._set_status, f"Running: {source}")
        try:
            columns, rows, truncated = limited_query(self.db_url, sql, self.limit)
        except Exception as exc:
            self.call_from_thread(self._set_status, f"Query failed: {exc}")
            return
        suffix = f"row limit reached: {self.limit}" if truncated else f"{len(rows)} rows"
        self.call_from_thread(self._set_status, f"{source} - {suffix}")
        self.call_from_thread(self._set_results, columns, rows)

    @work(thread=True)
    def preview(self, table: str) -> None:
        sql = f"select * from {quote_identifier(table)} limit 50"
        self.call_from_thread(self._set_sql, sql)
        self.call_from_thread(self._set_status, f"Previewing table: {table}")
        try:
            columns, rows = preview_table(self.db_url, table)
        except Exception as exc:
            self.call_from_thread(self._set_status, f"Preview failed: {exc}")
            return
        self.call_from_thread(self._set_status, f"Preview: {table} - {len(rows)} rows")
        self.call_from_thread(self._set_results, columns, rows)

    def _load_schema_tree(self) -> None:
        tree = self.query_one("#schema", Tree)
        tree.clear()
        tree.root.label = "Schema"
        for table, table_schema in inspect(self.db_url).items():
            table_node = tree.root.add(table, data=table)
            for column in table_schema.columns:
                foreign_key = next((fk for fk in table_schema.foreign_keys if fk.column == column.name), None)
                suffix = f" -> {foreign_key.referenced_table}.{foreign_key.referenced_column}" if foreign_key else ""
                table_node.add_leaf(f"{column.name} {column.type}{' pk' if column.primary_key else ''}{suffix}".rstrip())
        tree.root.expand()

    def _schema_text(self) -> str:
        lines = ["Schema", ""]
        for table, table_schema in inspect(self.db_url).items():
            lines.append(table)
            for column in table_schema.columns:
                foreign_key = next((fk for fk in table_schema.foreign_keys if fk.column == column.name), None)
                suffix = f" -> {foreign_key.referenced_table}.{foreign_key.referenced_column}" if foreign_key else ""
                lines.append(f"  {column.name} {column.type}{' pk' if column.primary_key else ''}{suffix}".rstrip())
            lines.append("")
        return "\n".join(lines).strip()

    def _set_sql(self, sql: str) -> None:
        self.query_one("#sql", TextArea).load_text(sql)

    def _set_status(self, message: str) -> None:
        self.query_one("#status", Static).update(message)

    def _set_results(self, columns: list[str], rows: list[tuple[object, ...]]) -> None:
        table = self.query_one("#results", DataTable)
        table.clear(columns=True)
        table.add_columns(*columns)
        for row in rows:
            table.add_row(*(str(value) for value in row))


def run_tui(db_url: str, model: str, limit: int = DEFAULT_LIMIT) -> None:
    AskSqlApp(db_url, model, limit).run()
